server:
  port: 1250
  error:
    include-message: always

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/xdisx?cachePrepStmts=true&useServerPrepStmts=true&rewriteBatchedStatements=true
    driver-class-name: org.postgresql.Driver
    username: root
    password: root
    hikari:
      minimumIdle: 5
      maximum-pool-size: 10
      schema: xdisx-security
  flyway:
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    schemas: ${spring.datasource.hikari.schema}
    default-schema: ${spring.datasource.hikari.schema}
    enabled: true
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
        ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
        default_schema: ${spring.datasource.hikari.schema}
jwt:
  secret: W6c5fP6fRvq+a5w+3YZkUm7clRmT4yr7/W+vJ9bxTV23HxzpVzFIfXS5JlFzvP+2xJY7+dLbFy1lx+oQy6YtvQ==
  expiration: 86400000

xdisx:
  cors:
    origins:
      - http://localhost:4200