name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  Continous-Docker-Build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Build with Gradle
        env:
          GITHUB_ACTOR: 'magraul'
        run: |
          chmod +x ./gradlew
          ./gradlew clean build
      - name: Login to GitHub Container Registry
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          echo "$GH_PAT" | docker login ghcr.io -u magraul --password-stdin

      - name: Build Docker Image and Push
        run: |
          docker build . --file Dockerfile --tag ghcr.io/magraul/xdisx-security:latest
          docker push ghcr.io/magraul/xdisx-security:latest
